### ISSUE TITLE
Debugging Help

### ISSUE THREAD

**Issue by gieskj01** [dpa99c/cordova-sqlite-porter#23]
When inspecting our android app I can see the following error:

polyfills.js:3 Unhandled Promise rejection: Cannot read property 'replace' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'replace' of undefined(…) TypeError: Cannot read property 'replace' of undefined
    at trimWhitespace (file:///android_asset/www/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:538:19)
    at applyStatements (file:///android_asset/www/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:88:41)
    at tx.executeSql.error.message (file:///android_asset/www/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:94:29)
    at SQLitePluginTransaction.handleStatementSuccess (file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:386:5)
    at Object.success (file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:412:18)
    at mycb (file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js:457:20)
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:293:58)
    at <anonymous>:1:9o @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): TypeError: Cannot read property 'replace' of undefined(…)

When drilling in to the executeSql.error.message get the following:
                function applyStatements() {
                    if (statements.length > 0) {
                        var statement = trimWhitespace(statements.shift());
                        tx.executeSql(statement, [], function(){
                            currentCount++;
                            if(opts.progressFn){
                                opts.progressFn(currentCount, totalCount);
                            }
                            applyStatements();
                        }, function (tx, error) {
                            error.message = "Failed to import SQL; message="+ error.message;
                            error.statement = statement;
                            handleError(error);
                        });
                    } else if(opts.successFn){
                        opts.successFn(totalCount);
                    }

I'm pretty confident there is a data quality issue with the data we are trying to import. We've found and eliminated special characters such as double single quotes and semi-colons. Can you provide any other insight into special characters or other potential data things we should look specifically for?

Thanks! Much appreciated for any help you can provide!

**Comment by dpa99c** [comment]
Please re-test with v1.0.0 of this plugin, which fixes some issues with escaping of special characters.

**Comment by dpa99c** [comment]
Closed due to no response from OP
